# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: zh-CN

# Change to your timezone
timezone: Asia/Shanghai

title: 飞扬BLOG # the main title
tagline: 顺风兮，逆风兮，无阻我飞扬 # subtitle
description: >-
  顺风兮，逆风兮，无阻我飞扬

url: "https://jhzmsc.github.io"

# github:
# username: jhzmsc # 已修改为你的用户名

social:
  name: 飞扬
  email: jhzmsc@outlook.com
  links:
     - https://jhzmsc.github.io # 第一条链接为版权所有者链接，已设为你的 GitHub
    # - https://twitter.com/username # 如果有推特可以取消注释

# Web Analytics Settings
analytics:
  goatcounter:
    id: jhzmsc  

# Page views settings
pageviews:
  provider: 'goatcounter'

# the avatar on sidebar
avatar: /assets/img/jhzmsc.jpg

# boolean type, the global switch for TOC in posts.
toc: true

# ↓↓↓ --- 评论系统配置（已根据你的脚本完成） --- ↓↓↓
comments:
  # 必须填入 giscus 才能开启全局开关
  provider: giscus 
  
  # Giscus 具体参数
  giscus:
    repo: 'jhzmsc/jhzmsc.github.io'
    repo_id: 'R_kgDOQ7-tzg'
    category: 'Announcements'
    category_id: 'DIC_kwDOQ7-tzs4C1GOU'
    mapping: 'pathname'
    strict: 0
    input_position: 'bottom'
    lang: 'zh-CN'
    reactions_enabled: 1
# ↑↑↑ --------------------------------------- ↑↑↑

paginate: 10
baseurl: ""

# ------------ 以下为系统默认参数，保持不变 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true # 确保文章默认开启评论
      toc: true 
      permalink: /posts/:title/
      last_modified_at: false
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
